// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsPacientesEvaluacion.Infrastructure.Persistence;

#nullable disable

namespace MsPacientesEvaluacion.Infrastructure.Migrations
{
    [DbContext(typeof(PacientesDbContext))]
    [Migration("20260814155811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MsPacientesEvaluacion.Domain.Aggregates.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NutricionistaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("MsPacientesEvaluacion.Domain.Aggregates.Paciente", b =>
                {
                    b.OwnsOne("MsPacientesEvaluacion.Domain.Entities.ConsultaInicial", "ConsultaInicial", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Altura")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("ConsultaInicial_Altura");

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("date")
                                .HasColumnName("ConsultaInicial_Fecha");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ConsultaInicial_Id");

                            b1.Property<decimal>("Peso")
                                .HasPrecision(8, 2)
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("ConsultaInicial_Peso");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Pacientes");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");

                            b1.OwnsOne("MsPacientesEvaluacion.Domain.Entities.Anamnesis", "Anamnesis", b2 =>
                                {
                                    b2.Property<Guid>("ConsultaInicialPacienteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("AntecedentesClinicos")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)")
                                        .HasColumnName("Anamnesis_AntecedentesClinicos");

                                    b2.Property<string>("HabitosAlimenticios")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)")
                                        .HasColumnName("Anamnesis_HabitosAlimenticios");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("Anamnesis_Id");

                                    b2.Property<string>("NecesidadesEspecificas")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("Anamnesis_NecesidadesEspecificas");

                                    b2.HasKey("ConsultaInicialPacienteId");

                                    b2.ToTable("Pacientes");

                                    b2.WithOwner()
                                        .HasForeignKey("ConsultaInicialPacienteId");
                                });

                            b1.Navigation("Anamnesis")
                                .IsRequired();
                        });

                    b.OwnsMany("MsPacientesEvaluacion.Domain.Entities.EvaluacionSeguimiento", "Evaluaciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Adherencia")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("date");

                            b1.Property<string>("Observaciones")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Peso")
                                .HasPrecision(8, 2)
                                .HasColumnType("decimal(8,2)");

                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PacienteId");

                            b1.ToTable("EvaluacionesSeguimiento", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");

                            b1.OwnsOne("MsPacientesEvaluacion.Domain.ValueObjects.Medidas", "Medidas", b2 =>
                                {
                                    b2.Property<Guid>("EvaluacionSeguimientoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Cadera")
                                        .HasPrecision(8, 2)
                                        .HasColumnType("decimal(8,2)")
                                        .HasColumnName("Medidas_Cadera");

                                    b2.Property<decimal>("Cintura")
                                        .HasPrecision(8, 2)
                                        .HasColumnType("decimal(8,2)")
                                        .HasColumnName("Medidas_Cintura");

                                    b2.Property<decimal>("Imc")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("decimal(6,2)")
                                        .HasColumnName("Medidas_Imc");

                                    b2.HasKey("EvaluacionSeguimientoId");

                                    b2.ToTable("EvaluacionesSeguimiento");

                                    b2.WithOwner()
                                        .HasForeignKey("EvaluacionSeguimientoId");
                                });

                            b1.Navigation("Medidas")
                                .IsRequired();
                        });

                    b.OwnsOne("MsPacientesEvaluacion.Domain.ValueObjects.DatosContacto", "Contacto", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Direccion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Contacto_Direccion");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Contacto_Email");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Contacto_Telefono");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Pacientes");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.Navigation("ConsultaInicial");

                    b.Navigation("Contacto")
                        .IsRequired();

                    b.Navigation("Evaluaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
