// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsProduccionAlimentos.Infrastructure.Persistence;

#nullable disable

namespace MsProduccionAlimentos.Infrastructure.Migrations
{
    [DbContext(typeof(NurTricenterDbContext))]
    partial class NurTricenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MsProduccionAlimentos.Domain.Aggregates.OrdenProduccion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EncargadoCocinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("LoteProduccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OrdenesProd", (string)null);
                });

            modelBuilder.Entity("MsProduccionAlimentos.Domain.Aggregates.Paquete", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Paquetes", (string)null);
                });

            modelBuilder.Entity("MsProduccionAlimentos.Domain.Aggregates.OrdenProduccion", b =>
                {
                    b.OwnsMany("MsProduccionAlimentos.Domain.Entities.ItemOrden", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CantidadPreparada")
                                .HasColumnType("int");

                            b1.Property<int>("CantidadRequerida")
                                .HasColumnType("int");

                            b1.Property<Guid>("OrdenProduccionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("RecetaId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("OrdenProduccionId");

                            b1.ToTable("OrdenItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrdenProduccionId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MsProduccionAlimentos.Domain.Aggregates.Paquete", b =>
                {
                    b.OwnsMany("MsProduccionAlimentos.Domain.Entities.Porcion", "Porciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Cantidad")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)");

                            b1.Property<bool>("EstaEnvasada")
                                .HasColumnType("bit");

                            b1.Property<Guid>("PaqueteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("RecetaId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PaqueteId");

                            b1.ToTable("Porciones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaqueteId");
                        });

                    b.OwnsOne("MsProduccionAlimentos.Domain.ValueObjects.Etiqueta", "Etiqueta", b1 =>
                        {
                            b1.Property<Guid>("PaqueteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DireccionEntrega")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Etiqueta_DireccionEntrega");

                            b1.Property<string>("NombrePaciente")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Etiqueta_NombrePaciente");

                            b1.Property<string>("NumeroId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Etiqueta_NumeroId");

                            b1.HasKey("PaqueteId");

                            b1.ToTable("Paquetes");

                            b1.WithOwner()
                                .HasForeignKey("PaqueteId");
                        });

                    b.Navigation("Etiqueta")
                        .IsRequired();

                    b.Navigation("Porciones");
                });
#pragma warning restore 612, 618
        }
    }
}
